env:
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
rules:
  no-undef: off
  import/extensions: off
